services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        mode: ingress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M   # Max memory usage limit
        reservations:
          memory: 256M   # Ensures 256MB is always available
