services:
  fastapi:
    restart: always
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - target: 8000
        published: 8000
        mode: ingress
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
